### ISSUE TITLE
Highlight automatically are not there

### ISSUE THREAD

**Issue by Serhioromano** [highlightjs/highlightjs-structured-text#15]
@marcoscaceres please look at this topic.

https://github.com/microsoft/vscode-markdown-tm-grammar/issues/79

They say that VS Code uses HighlightJS to Highlight markdown previews. Why it does not highlight this language? Can you ship next HLJS version with support of this language out of the box.

The whole purpose of my integration was that with time as developers update HLJS version in their applications on different blogs platforms, highlight of ST will appear. But it is for years already and situation does not change. Please tell me what to do to make it part of HLJS install through NPM or Bower.

**Comment by joshgoebel** [comment]
> Can you ship next HLJS version with support of this language out of the box.

Short version: The core team does not currently have time to merge, support and maintain additional languages.

Please see for the larger discussion:
https://github.com/highlightjs/highlight.js/issues/2149

**Comment by joshgoebel** [comment]
Sorry, perhaps I should not have actually closed this, as the repo is your own. :)  I saw you writing to Marco and in the moment assumed he maintains the grammar and therefore I closed it in my capacity as a member of the core team.

Feel free to reopen if you wish (for some reason), but that doesn't change the answer given.

**Comment by joshgoebel** [comment]
> The whole purpose of my integration was that with time as developers update HLJS version in their applications on different blogs platforms, highlight of ST will appear. 

_FYI: This is also a misunderstanding in MANY cases._ This would **only** be true if one used the `npm` version... for those using the web version most use our common build (or a custom build) - which does not include all grammars - even first party ones - as the size of the final build would be huge if that were to be the case.

**Comment by Serhioromano** [comment]
@joshgoebel I also do not understand separation of repository like mine and `src/languages` folder. I could add my language there why it is not there? At first, I added it there and it worked, but later marco said that HLJS goes to new architecture where every language is going to be separate repository. He asked me to change mine. I did. But now I am not in `src/languages`. 

I mean I am so confused at what should I do to make it work like you intent it to work.

**Comment by joshgoebel** [comment]
> I also do not understand separation of repository like mine and src/languages folder. 

_src/languages are first-party grammars._ The core team supports them, maintains them, fixes bugs (as we can), etc.  We do not currently have time to support, maintain, and fix issues with additional grammars. So any new grammars are 3rd party grammars.  It's the authors responsibility to maintain them, fix bugs, etc.  It is a users responsibility to install them separately IF needed (which is typically just a single line of code, etc).

We provide repos here (at the main organization) only as a courtesy.  

Again if you want additional detail on WHY this is how it is, the larger discussion is all here: https://github.com/highlightjs/highlight.js/issues/2149

> I mean I am so confused at what should I do to make it work like you intent it to work.

To create the `dist` folder (which we recommend all 3rd party grammars have) see my instructions in the other thread.  That's the best you can do - make it easy for users to install your grammar - if they choose to do so.
