### ISSUE TITLE
Problem exporting to pdf.

### ISSUE THREAD

**Issue by Wesztman** [highlightjs/highlightjs-structured-text#16]
Hi there! 

I can't find any VSCode markdown extension which is able to export this syntax highlighting to pdf, do you have any tips?

I get the highlighting in the code editor, and with marp I get one slide, but I need it for a regular pdf document and there I always only get all black text.

**Comment by Serhioromano** [comment]
First read this

https://github.com/highlightjs/highlightjs-structured-text/issues/9#issuecomment-685266264

Then, what do you use for PDF creation? For instance I write book on gitbook with markdown and I created command to create PDF and there I do all highlights.
