### ISSUE TITLE
Invite to communicate for @joshgoebel

### ISSUE THREAD

**Issue by Serhioromano** [highlightjs/highlightjs-structured-text#17]
@joshgoebel

Thank you for response first of all. But i am completely lost how to add my own language. In `extra/3RD_PARTY_QUICK_START.md` file is a very controversial and convoluted information.

1. It shows as example separate repositories like mine but suggest to checkout HLJS repo and add folder to `extra` folder
2. It suggests adding folder `extra/iecst` in my case but later when run build it says it will generate `extra/highlightjs-iecst/dist/iecst.min.js` file. So, it is a different folder name.
3. In instruction is say create file in `src/languages` but why then create separate repository?

**Comment by joshgoebel** [comment]
> It suggests adding folder extra/iecst in my case but later when run build it says it will generate extra/highlightjs-iecst/dist/iecst.min.js file. So, it is a different folder name.

_The name of the folder is entirely irrelevant._  `highlightjs-[grammar]` is the convention for naming repos.  But any folder name will work.

- your folder is `extra/booger` and your JS file is `booger.js`
- your distributable file will be `extra/booger/dist/booger.js`



> In instruction is say create file in src/languages but why then create separate repository?

It says clearly: 

> create an `extra/xyz` folder ... **All paths below are relative to that.**

The src/languages folder belongs in your repository.  So each grammar repository matches a familiar structure. Again see any other of the grammar repos for examples.

---

More than happy for PRs to improve the documentation.

**Comment by joshgoebel** [comment]
> In instruction is say create file in src/languages but why then create separate repository?

https://github.com/highlightjs/highlight.js/issues/2149

> It suggests adding folder extra/iecst in my case but later when run build it says it will generate extra/highlightjs-iecst/dist/iecst.min.js file. So, it is a different folder name.

**The name isn't relevant at all.**

_Whatever_ you name the folder is where it will place the `dist` folder.

**Comment by Serhioromano** [comment]
@joshgoebel do you mean that I use HLJS main repository to generate dist/*min.js and then I move it to my repository and comit?

**Comment by joshgoebel** [comment]
Not exactly.

_You check out your repository INSIDE the HLJS repository, inside `extra`._  That's what the `extra` folder is for.

Then there is no need to "move" anything.  You just git add and git commit it.

**Comment by Serhioromano** [comment]
Done. Now iv'got it. Updated to new version now. Hope this is how it should be now.

**Comment by joshgoebel** [comment]
Looks good.

You shouldn't need the `iecst.js` in your root anymore though.
