### ISSUE TITLE
Please push new release to NPM

### ISSUE THREAD

**Issue by philippn** [highlightjs/highlightjs-structured-text#20]
Hi there,

first of all, thanks for your great work. I have seen, that you have updated the dependencies two months ago in order to use the new NPM highlight.js instead of the deprecated one.

However, the release currently being distributed via NPM still yields the old dependency and thus brings up this warning:

> npm WARN deprecated highlightjs@9.16.2: Use the 'highlight.js' package instead https://npm.im/highlight.js

Could you please release a new version to fix this?

Thanks in advance and kind regards,
Philipp

**Comment by Serhioromano** [comment]
I added an action. Each time I bush to master, new version will be generated and published to NPM.
