### ISSUE TITLE
docusaurus support

### ISSUE THREAD

**Issue by kdpuvvadi** [highlightjs/highlightjs-structured-text#23]
`highligh.js` is already included  in the [docusaurus](https://github.com/facebook/docusaurus). How do we import `highlightjs-structured-text` use for `st`. 

Thanks.

**Comment by Serhioromano** [comment]
[docusaurus](https://github.com/facebook/docusaurus) has to have interface to configure HLJS. In that point you can inject this highlight.

**Comment by Serhioromano** [comment]
@kdpuvvadi  If you solved this, I would look at how it is done and add example to readme.
